[package]
name = "webauthn"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
base64 = "0.23.1"
bitcoin = "0.32.102"
console_log = "1.1.0"
getrandom = { version = "0.4.3", features = ["wasm_js"] }
hex = "0.4.3"
hkdf = "0.13.0"
log = "0.4.34"
rand = "0.10.2"
sha2 = "0.11.0"
uuid = { version = "1.25.0", features = ["rng-rand", "v4"] }
web-sys = { version = "0.3.104", features = [
    "AuthenticationExtensionsClientInputs",
    "AuthenticationExtensionsClientOutputs",
    "AuthenticationExtensionsPrfInputs",
    "AuthenticationExtensionsPrfOutputs",
    "AuthenticationExtensionsPrfValues",
    "CredentialCreationOptions",
    "CredentialsContainer",
    "CredentialRequestOptions",
    "Navigator",
    "PublicKeyCredential",
    "PublicKeyCredentialCreationOptions",
    "PublicKeyCredentialDescriptor",
    "PublicKeyCredentialParameters",
    "PublicKeyCredentialRequestOptions",
    "PublicKeyCredentialRpEntity",
    "PublicKeyCredentialType",
    "PublicKeyCredentialUserEntity",
    "Storage",
    "StorageManager",
    "Window",
] }
